name: build
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - run: "Get-ChildItem Env:"
      - name: Create output dir
        run: mkdir out
        
      - name: Configure the project.
        run: cmake -D CMAKE_TOOLCHAIN_FILE=c:\vcpkg\scripts\buildsystems\vcpkg.cmake %GITHUB_WORKSPACE%
        working-directory: $GITHUB_WORKSPACE/out

      - name: Build the project.
        run: cmake --build out
