name: main
on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          lfs: true

      - uses: lukka/get-cmake@latest

      - name: Setup anew (or from cache) vcpkg (and does not build any package)
        uses: lukka/run-vcpkg@v11 
        with:
          vcpkgGitCommitId: 'ce613c41372b23b1f51333815feb3edd87ef8a8b'

      - name: Run CMake consuming CMakePreset.json and run vcpkg to build packages
        uses: lukka/run-cmake@v10
        with:
          configurePreset: 'ninja-multi-vcpkg'
          buildPreset: 'ninja-multi-vcpkg'
          buildPresetAdditionalArgs: "['--config Release']"

      - uses: actions/upload-artifact@v4
        with:
          name: windows
          path: builds/ninja-multi-vcpkg/Release
      
      - name: "Create latest release file"
        run: |
          Get-ChildItem -Path builds/ninja-multi-vcpkg/Release | Compress-Archive -DestinationPath windows-latest.zip
          
      - uses: EndBug/latest-tag@latest
        
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body: |
            This is the latest, the bleeding edge. Might not work properly and might harm your system. Use with care.
          files: windows-latest.zip
          name: Latest
          prerelease: true
          tag_name: latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
