name: non-main
on: 
  push:
    branches-ignore:
      - main
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: true

      - name: Create output dir
        run: mkdir out
        
      - name: Configure the project.
        run: cmake $env:GITHUB_WORKSPACE
        working-directory: out

      - name: Build the project.
        run: cmake --build out --config Release
      
      - uses: actions/upload-artifact@v3
        with:
          name: windows
          path: out/Release